server:
  error:
    include-message: always

  forward-headers-strategy: framework

  port: 38983

  servlet:
    context-path: /crossfyre

spring:
  application:
    name: service

  jackson:
    deserialization:
      accept-float-as-int: false

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com