spring:
  application:
    name: crossfyre

  profiles:
    active:
      - service
      - local

  datasource:
    url: "jdbc:h2:file:./db/crossfyre"

  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true

  sql:
    init:
      mode: always
