spring:
  application:
    name: preload

  main:
    web-application-type: none

crossfyre:
  preload:
    # noinspection SpringBootApplicationYaml
    file:
      puzzle: preload/puzzle.json
      words: preload/words.json
