remote_theme: ddc-java/ddc-day-book
repository_link:
  enabled: false
page_navigator:
  enabled: true
titles_from_headings:
  enabled: false
prev_next_navigation:
- bottom

# DONE Modify the contents below for the specific project. NOTE THE INDENTATION!

title: "CrossFyre"
description: "Crossword Generator Game Application"

# DONE List team members in the author.name property.

author:
  name: "Dorian Obisike, Travis Hollins, and Tim Nickell"

# Do not change the following line.
  copyright: true
